# Generated by Django 5.0.7 on 2024-07-26 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_profile_created_at_remove_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
