# Generated by Django 5.0.7 on 2024-07-27 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_post_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamps',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
