# Generated by Django 5.0.7 on 2024-07-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_post_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamps',
            field=models.DateTimeField(default='timezone.now'),
        ),
    ]
