# Generated by Django 5.0.7 on 2024-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_post_likes_like_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
