# Generated by Django 5.0.7 on 2024-07-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_post_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamps',
            field=models.DateTimeField(default=''),
        ),
    ]
