# Generated by Django 5.0.7 on 2024-07-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_profile_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='profile_picture',
            new_name='profile',
        ),
    ]
