# Generated by Django 5.0.7 on 2024-07-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_remove_follow_following_follow_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
