# Generated by Django 5.0.7 on 2024-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='social.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, to='social.post'),
        ),
    ]
