# Generated by Django 5.0.7 on 2024-08-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_remove_profile_following_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower', to='social.profile'),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
