# Generated by Django 5.0.7 on 2024-08-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
