# Generated by Django 5.0.7 on 2024-08-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
