# Generated by Django 5.0.7 on 2024-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_message_message_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static/assets1/default-user.png', null=True, upload_to='media/'),
        ),
    ]
